#!/usr/bin/env bash

set -euo pipefail

source ./read-secret-var

read_secret_var CA_ROOT_CERT all
read_secret_var CA_ROOT_KEY all
export CERT_USER=etcd
export CERT_GROUP=etcd
gen-ssl
unset CA_ROOT_CERT CA_ROOT_KEY

chmod go+x /usr/local/etc

export ETCD_NAME="${ETCD_NAME:=$HOSTNAME}"

export ETCD_DATA_DIR=/var/etcd-data
export ETCD_INITIAL_ADVERTISE_PEER_URLS=https://${HOSTNAME}:2380
export ETCD_ADVERTISE_CLIENT_URLS=https://${HOSTNAME}:2379
export ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
export ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379

export ETCD_CERT_FILE=/usr/local/etc/ssl/server.crt
export ETCD_KEY_FILE=/usr/local/etc/ssl/server.key
export ETCD_CLIENT_CERT_AUTH=true
export ETCD_TRUSTED_CA_FILE=/usr/local/etc/ssl/ca-root.crt

export ETCD_PEER_CERT_FILE=/usr/local/etc/ssl/peer.crt
export ETCD_PEER_KEY_FILE=/usr/local/etc/ssl/peer.key
export ETCD_PEER_CLIENT_CERT_AUTH=true
export ETCD_PEER_TRUSTED_CA_FILE=/usr/local/etc/ssl/ca-root.crt

export ETCD_AUTO_COMPACTION_MODE="${ETCD_AUTO_COMPACTION_MODE:-periodic}"
export ETCD_AUTO_COMPACTION_RETENTION="${ETCD_AUTO_COMPACTION_RETENTION:-1h}"

read_secret_var ETCD_INITIAL_CLUSTER_TOKEN

chown -R etcd:etcd /var/etcd-data/
chmod 0700 /var/etcd-data/
chown -R etcd:etcd /etc/etcd/

# try to add node to an existing cluster
if [[ "$ETCD_INITIAL_CLUSTER_STATE" == "existing" ]]; then
  echo "Adding to existing cluster"

  # fail if data directory is not empty when joining an existing cluster
  if [ -d "$ETCD_DATA_DIR" ] && [ "$(ls -A "$ETCD_DATA_DIR")" ]; then
    echo "Error: $ETCD_DATA_DIR must be empty when joining an existing cluster" >&2
    exit 1
  fi

  member_json=$(etcdctl --endpoints "$ETCD_ENDPOINTS" member list -w json | jq -c ".members[] | select(.peerURLs[]? == \"$ETCD_INITIAL_ADVERTISE_PEER_URLS\")" || true)
  if [[ -n "$member_json" ]]; then
    member_id=$(echo "$member_json" | jq -r '.ID')
    if [[ -n "$member_id" ]]; then
      member_id_hex=$(printf '%x\n' "$member_id" || true)
      echo "Removing existing member id=${member_id_hex} for $ETCD_NAME"
      etcdctl --endpoints "$ETCD_ENDPOINTS" member remove "${member_id_hex}" || true
    fi
  fi

  echo "Adding member $ETCD_NAME"
  MEMBER_ADD_OUT=$(mktemp)
  etcdctl --endpoints "$ETCD_ENDPOINTS" member add "$ETCD_NAME" --peer-urls="$ETCD_INITIAL_ADVERTISE_PEER_URLS" >"${MEMBER_ADD_OUT}" 2>&1 || true
  export ETCD_INITIAL_CLUSTER=$(grep 'ETCD_INITIAL_CLUSTER=' "${MEMBER_ADD_OUT}" | awk -F'"' '{print $2}')
  if [ -z "${ETCD_INITIAL_CLUSTER}" ]; then
    echo "Failed to add member $ETCD_NAME"
    echo "$MEMBER_ADD_OUT"
    rm "$MEMBER_ADD_OUT"
    exit 1
  fi
  rm "$MEMBER_ADD_OUT"
fi

exec su-exec etcd etcd
