flowchart TB
    subgraph Clients
        C1[Client Apps]
    end
    subgraph Load Balancing
        HAP1[HAProxy 1<br/>:5432 RW / :5433 RO]
        HAP2[HAProxy 2<br/>:5432 RW / :5433 RO]
    end
    subgraph PostgreSQL Cluster
        subgraph Node1[Patroni Node 1]
            PG1[(PostgreSQL<br/>Primary)]
            PGB1[PgBouncer<br/>:6432]
            PAT1[Patroni<br/>:8008]
        end
        subgraph Node2[Patroni Node 2]
            PG2[(PostgreSQL<br/>Replica)]
            PGB2[PgBouncer<br/>:6432]
            PAT2[Patroni<br/>:8008]
        end
        subgraph Node3[Patroni Node 3]
            PG3[(PostgreSQL<br/>Replica)]
            PGB3[PgBouncer<br/>:6432]
            PAT3[Patroni<br/>:8008]
        end
    end
    subgraph Consensus
        ETCD1[etcd 1<br/>:2379]
        ETCD2[etcd 2<br/>:2379]
        ETCD3[etcd 3<br/>:2379]
    end
    subgraph Backup Storage
        S3[(S3 Bucket)]
    end
    C1 -->|TLS| HAP1
    C1 -->|TLS| HAP2
    
    HAP1 -->|mTLS| PGB1
    HAP1 -->|mTLS| PGB2
    HAP1 -->|mTLS| PGB3
    HAP2 -->|mTLS| PGB1
    HAP2 -->|mTLS| PGB2
    HAP2 -->|mTLS| PGB3
    PGB1 -->|Unix Socket| PG1
    PGB2 -->|Unix Socket| PG2
    PGB3 -->|Unix Socket| PG3
    PAT1 <-->|mTLS| ETCD1
    PAT1 <-->|mTLS| ETCD2
    PAT1 <-->|mTLS| ETCD3
    PAT2 <-->|mTLS| ETCD1
    PAT2 <-->|mTLS| ETCD2
    PAT2 <-->|mTLS| ETCD3
    PAT3 <-->|mTLS| ETCD1
    PAT3 <-->|mTLS| ETCD2
    PAT3 <-->|mTLS| ETCD3
    ETCD1 <-->|mTLS| ETCD2
    ETCD2 <-->|mTLS| ETCD3
    ETCD3 <-->|mTLS| ETCD1
    PG1 -->|Physical Backup - pgBackRest<br/>full/incr/WAL| S3
    PG1 -->|Logical Backup - pg_dump| S3
