x-cert-vars: &cert-vars
  CA_ROOT_CERT:
  CA_ROOT_KEY:
  CERT_C:
  CERT_ST:
  CERT_L:
  CERT_O:
  CERT_OU:
  CERT_CN:
  CERT_EXPIRY:
  CERT_KEY_ALGO:
  CERT_KEY_SIZE:
  CERT_SAN_IP:
  CERT_SAN_DNS:

x-etcd-vars: &etcd-vars
  <<: *cert-vars
  ETCD_INITIAL_CLUSTER: etcd_01=https://etcd_01:2380,etcd_02=https://etcd_02:2380,etcd_03=https://etcd_03:2380
  ETCD_INITIAL_CLUSTER_STATE: new
  # ETCD_INITIAL_CLUSTER_TOKEN: file:/run/secrets/etcd_initial_cluster_token

# x-etcd-secrets: &etcd-secrets
# - ca_root_cert
# - ca_root_key
# - etcd_initial_cluster_token

x-pg-vars: &pg-vars
  <<: *cert-vars
  ETCD_HOSTS: etcd_01:2379,etcd_02:2379,etcd_03:2379
  CLUSTER:
  POSTGRES_SU_USER: postgres
  # POSTGRES_SU_PWD: file:/run/secrets/postgres_su_password
  POSTGRES_SU_PWD: ssm:/prod/db/postgres/password/su
  POSTGRES_REPL_USER: replicator
  # POSTGRES_REPL_PWD: file:/run/secrets/postgres_repl_password
  # POSTGRES_REPL_PWD: file:/run/secrets/postgres_repl_password
  POSTGRES_REPL_PWD: ssm:/prod/db/postgres/password/repl
  POSTGRES_REWIND_USER: rewinder
  # POSTGRES_REWIND_PWD: file:/run/secrets/postgres_rewind_password
  POSTGRES_REWIND_PWD: ssm:/prod/db/postgres/password/rewind
  POSTGRES_SUBNET:
  POSTGRES_ARCHIVE_TIMEOUT: 300
  BACKUP_NAME:
  # BACKUP_REGION: file:/run/secrets/backup_region
  BACKUP_REGION: ssm:/prod/db/postgres/physical/backup/region
  # BACKUP_PATH: file:/run/secrets/backup_path
  BACKUP_PATH: ssm:/prod/db/postgres/physical/backup/path
  # BACKUP_ACCESS_KEY: file:/run/secrets/backup_access_key
  BACKUP_ACCESS_KEY:
  # BACKUP_SECRET_KEY: file:/run/secrets/backup_secret_key
  BACKUP_SECRET_KEY:
  BACKUP_CRON_FULL: ssm:/prod/db/postgres/physical/backup/cron/full
  BACKUP_CRON_INCR: ssm:/prod/db/postgres/physical/backup/cron/incr
  RESTORE_NAME:
  # RESTORE_REGION: file:/run/secrets/restore_region
  RESTORE_REGION: ssm:/prod/db/postgres/physical/restore/region
  # RESTORE_PATH: file:/run/secrets/restore_path
  RESTORE_PATH: ssm:/prod/db/postgres/physical/restore/path
  # RESTORE_ACCESS_KEY: file:/run/secrets/restore_access_key
  RESTORE_ACCESS_KEY:
  # RESTORE_SECRET_KEY: file:/run/secrets/restore_secret_key
  RESTORE_SECRET_KEY:

# x-pg-secrets: &pg-secrets
# - ca_root_cert
# - ca_root_key
# - postgres_su_password
# - postgres_repl_password
# - postgres_rewind_password
# - backup_path
# - backup_region
# - backup_access_key
# - backup_secret_key
# - restore_path
# - restore_region
# - restore_access_key
# - restore_secret_key

services:
  etcd_01:
    build: ./etcd
    image: postgres-patroni/etcd:latest
    container_name: etcd_01
    hostname: etcd_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_01_data:/var/etcd-data
    environment: *etcd-vars
    env_file:
      - .env
    # secrets: *etcd-secrets
    networks:
      cluster:

  etcd_02:
    image: postgres-patroni/etcd:latest
    container_name: etcd_02
    hostname: etcd_02
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_02_data:/var/etcd-data
    environment: *etcd-vars
    env_file:
      - .env
    # secrets: *etcd-secrets
    networks:
      cluster:

  etcd_03:
    image: postgres-patroni/etcd:latest
    container_name: etcd_03
    hostname: etcd_03
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_03_data:/var/etcd-data
    environment: *etcd-vars
    env_file:
      - .env
    # secrets: *etcd-secrets
    networks:
      cluster:

  pg_01:
    build: ./patroni
    image: postgres-patroni/patroni:latest
    container_name: pg_01
    hostname: pg_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - pg_01_data:/var/lib/postgresql
    environment: *pg-vars
    env_file:
      - .env
    # secrets: *pg-secrets
    networks:
      cluster:
    depends_on:
      - etcd_01
      - etcd_02
      - etcd_03

  pg_02:
    image: postgres-patroni/patroni:latest
    container_name: pg_02
    hostname: pg_02
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - pg_02_data:/var/lib/postgresql
    environment: *pg-vars
    env_file:
      - .env
    # secrets: *pg-secrets
    networks:
      cluster:
    depends_on:
      - etcd_01
      - etcd_02
      - etcd_03

  haproxy_01:
    build: ./haproxy
    image: postgres-patroni/haproxy:latest
    container_name: haproxy_01
    hostname: haproxy_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    environment:
      <<: *cert-vars
      TARGETS: pg_01:6432,pg_02:6432
    env_file:
      - .env
    # secrets:
    # - ca_root_cert
    # - ca_root_key
    depends_on:
      - pg_01
      - pg_02
    networks:
      cluster:
    ports:
      - 5432:5432
      - 5433:5433

# secrets:
# ca_root_cert:
#   file: ./secrets/ca_root_cert
# ca_root_key:
#   file: ./secrets/ca_root_key
# etcd_initial_cluster_token:
#   file: ./secrets/etcd_initial_cluster_token
# postgres_su_password:
#   file: ./secrets/postgres_su_password
# postgres_repl_password:
#   file: ./secrets/postgres_repl_password
# postgres_rewind_password:
#   file: ./secrets/postgres_rewind_password
# backup_path:
#   file: ./secrets/backup_path
# backup_region:
#   file: ./secrets/backup_region
# backup_access_key:
#   file: ./secrets/backup_access_key
# backup_secret_key:
#   file: ./secrets/backup_secret_key
# restore_path:
#   file: ./secrets/restore_path
# restore_region:
#   file: ./secrets/restore_region
# restore_access_key:
#   file: ./secrets/restore_access_key
# restore_secret_key:
#   file: ./secrets/restore_secret_key

volumes:
  etcd_01_data:
  etcd_02_data:
  etcd_03_data:
  pg_01_data:
  pg_02_data:

networks:
  cluster:
    driver: bridge
