services:
  etcd_01:
    build: ./etcd
    container_name: etcd_01
    hostname: etcd_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_01_data:/var/etcd-data
    environment:
      ETCD_INITIAL_CLUSTER: etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380
    networks:
      etcd_cluster:

  etcd_02:
    build: ./etcd
    container_name: etcd_02
    hostname: etcd_02
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_02_data:/var/etcd-data
    environment:
      ETCD_INITIAL_CLUSTER: etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380
    networks:
      etcd_cluster:

  pg_01:
    build: ./patroni
    container_name: pg_01
    hostname: pg_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - pg_01_data:/var/lib/postgresql
    environment:
      ETCD_01: etcd_01
      ETCD_02: etcd_02
      POSTGRES_USER: postgres
      POSTGRES_PWD: password
      POSTGRES_SUBNET: "0.0.0.0/0"
      BACKUP_NAME:
      BACKUP_REGION:
      BACKUP_PATH:
      BACKUP_ACCESS_KEY:
      BACKUP_SECRET_KEY:
    networks:
      etcd_cluster:

  pg_02:
    build: ./patroni
    container_name: pg_02
    hostname: pg_02
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - pg_02_data:/var/lib/postgresql
    environment:
      ETCD_01: etcd_01
      ETCD_02: etcd_02
      POSTGRES_USER: postgres
      POSTGRES_PWD: password
      POSTGRES_SUBNET: "0.0.0.0/0"
      BACKUP_NAME:
      BACKUP_REGION:
      BACKUP_PATH:
      BACKUP_ACCESS_KEY:
      BACKUP_SECRET_KEY:
    networks:
      etcd_cluster:

volumes:
  etcd_01_data:
  etcd_02_data:
  pg_01_data:
  pg_02_data:

networks:
  etcd_cluster:
    driver: bridge
