services:
  etcd_01:
    image: etcd
    container_name: etcd_01
    hostname: etcd_01
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_01_data:/var/etcd-data
    environment:
      ETCD_INITIAL_CLUSTER: etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380
    networks:
      etcd_cluster:

  etcd_02:
    image: etcd
    container_name: etcd_02
    hostname: etcd_02
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_02_data:/var/etcd-data
    environment:
      ETCD_INITIAL_CLUSTER: etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380
    networks:
      etcd_cluster:

volumes:
  etcd_01_data:
  etcd_02_data:

networks:
  etcd_cluster:
    driver: bridge
