x-cert-vars: &cert-vars
  CA_ROOT_CERT:
  CA_ROOT_KEY:
  CERT_C:
  CERT_ST:
  CERT_L:
  CERT_O:
  CERT_OU:
  CERT_CN:
  CERT_EXPIRY:
  CERT_KEY_ALGO:
  CERT_KEY_SIZE:
  CERT_SAN_IP:
  CERT_SAN_DNS:

x-pg-vars: &pg-vars
  <<: *cert-vars
  ETCD_HOSTS: etcd_01:2379,etcd_02:2379,etcd_03:2379
  CLUSTER:
  BACKUP_NAME:
  # BACKUP_REGION: file:/run/secrets/backup_region
  # BACKUP_REGION: ssm:/prod/db/postgres/physical/backup/region
  # BACKUP_PATH: file:/run/secrets/backup_path
  # BACKUP_PATH: ssm:/prod/db/postgres/physical/backup/path
  # BACKUP_ACCESS_KEY: file:/run/secrets/backup_access_key
  # BACKUP_ACCESS_KEY:
  # BACKUP_SECRET_KEY: file:/run/secrets/backup_secret_key
  # BACKUP_SECRET_KEY:
  # BACKUP_CRON_FULL: ssm:/prod/db/postgres/physical/backup/cron/full
  # BACKUP_CRON_INCR: ssm:/prod/db/postgres/physical/backup/cron/incr

x-pg-secrets: &pg-secrets
  - ca_root_cert
  - ca_root_key
# - backup_path
# - backup_region
# - backup_access_key
# - backup_secret_key

services:
  pg_01:
    build: ./patroni
    image: postgres-patroni/patroni:latest
    container_name: pg_01
    command: ["--upgrade"]
    hostname: pg_01
    restart: no 
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - pg_01_data:/var/lib/postgresql
    environment: *pg-vars
    env_file:
      - .env
    secrets: *pg-secrets
    networks:
      cluster:

secrets:
  ca_root_cert:
    file: ./secrets/ca_root_cert
  ca_root_key:
    file: ./secrets/ca_root_key
# backup_path:
#   file: ./secrets/backup_path
# backup_region:
#   file: ./secrets/backup_region
# backup_access_key:
#   file: ./secrets/backup_access_key
# backup_secret_key:
#   file: ./secrets/backup_secret_key

volumes:
  pg_01_data:

networks:
  cluster:
    driver: bridge
