#!/usr/bin/env bash

set -euo pipefail

upgrade_pg_data=0
for arg in "$@"; do
  [[ "$arg" == "--upgrade-pg-data" ]] && upgrade_pg_data=1 && break
done

source ./read-secret-var

mkdir -p /var/lib/postgresql/data
chown postgres:postgres /var/lib/postgresql/data
chmod 0750 /var/lib/postgresql/data

mkdir -p /run/postgresql
chown postgres:postgres /run/postgresql
chmod 0750 /run/postgresql

if [[ -z "${CLUSTER:-}" ]]; then
  echo "Missing CLUSTER var"
  exit 1
fi

read_secret_var CA_ROOT_CERT all
read_secret_var CA_ROOT_KEY all
export CERT_USER=postgres
export CERT_GROUP=postgres
gen-ssl
unset CA_ROOT_CERT CA_ROOT_KEY

read_secret_var POSTGRES_SU_PWD
read_secret_var POSTGRES_REPL_PWD
read_secret_var POSTGRES_REWIND_PWD
read_secret_var BACKUP_PATH
read_secret_var BACKUP_REGION
read_secret_var BACKUP_ACCESS_KEY
read_secret_var BACKUP_SECRET_KEY
read_secret_var BACKUP_CRON_FULL
read_secret_var BACKUP_CRON_INCR
read_secret_var RESTORE_PATH
read_secret_var RESTORE_REGION
read_secret_var RESTORE_ACCESS_KEY
read_secret_var RESTORE_SECRET_KEY
read_secret_var DUMP_CRON

# backup/restore config
export BACKUP_NAME="${BACKUP_NAME:=$CLUSTER}"
export BACKUP_ACCESS_KEY="${BACKUP_ACCESS_KEY:=${AWS_ACCESS_KEY_ID:=}}"
export BACKUP_SECRET_KEY="${BACKUP_SECRET_KEY:=${AWS_SECRET_ACCESS_KEY:=}}"

export RESTORE_NAME="${RESTORE_NAME:=$BACKUP_NAME}"
export RESTORE_PATH="${RESTORE_PATH:=$BACKUP_PATH}"
export RESTORE_REGION="${RESTORE_REGION:=$BACKUP_REGION}"
export RESTORE_ACCESS_KEY="${RESTORE_ACCESS_KEY:=${BACKUP_ACCESS_KEY:=}}"
export RESTORE_SECRET_KEY="${RESTORE_SECRET_KEY:=${BACKUP_SECRET_KEY:=}}"

pgbackrest-write-conf

# patroni config
NI=$(ip -4 route show default | awk '{print $5}')
export POSTGRES_SUBNET="${POSTGRES_SUBNET:-$(ip -4 route | awk -v i="$NI" '$0 ~ i && /scope link/ {print $1; exit}')}"

export POSTGRES_ARCHIVE_TIMEOUT="${POSTGRES_ARCHIVE_TIMEOUT:-0}"
export POSTGRES_SHARED_BUFFERS="${POSTGRES_SHARED_BUFFERS:-128MB}"
export POSTGRES_JIT="${POSTGRES_JIT:-on}"
export POSTGRES_JIT_ABOVE_COST="${POSTGRES_JIT_ABOVE_COST:-100000}"

envsubst </venv/etc/patroni-template.yml >/venv/etc/patroni.yml

# upgrade pg data
if [[ "$upgrade_pg_data" == "1" ]]; then
  source ./upgrade-pg-data
  if upgrade_pg_data; then
    exit 0
  else
    exit 1
  fi
fi

# backup/dump schedules
if [[ -n "${BACKUP_CRON_FULL:-}" || -n "${BACKUP_CRON_INCR:-}" || -n "${DUMP_CRON:-}" ]]; then
  {
    if [[ -n "${BACKUP_CRON_FULL:-}" ]]; then
      echo "$BACKUP_CRON_FULL /usr/local/bin/pgbackrest-backup full >> /proc/1/fd/1 2>> /proc/1/fd/2"
    fi
    if [[ -n "${BACKUP_CRON_INCR:-}" ]]; then
      echo "$BACKUP_CRON_INCR /usr/local/bin/pgbackrest-backup incr >> /proc/1/fd/1 2>> /proc/1/fd/2"
    fi
    if [[ -n "${DUMP_CRON:-}" ]]; then
      echo "$DUMP_CRON /usr/local/bin/postgres-dump-all >> /proc/1/fd/1 2>> /proc/1/fd/2"
    fi
  } | crontab -
  crond -b -l 8 || true
fi

# disable backup config if required
if [[ -z "${BACKUP_PATH:-}" ]]; then
  sed -i '/^\s*# BACKUP_BEGIN\s*$/,/^\s*# BACKUP_END\s*$/d' /venv/etc/patroni.yml
fi

# disable restore config if required
if [[ -z "${RESTORE_PATH:-}" ]]; then
  sed -i '/^\s*# RESTORE_BEGIN\s*$/,/^\s*# RESTORE_END\s*$/d' /venv/etc/patroni.yml
fi

# pgbouncer
mkdir -p /var/log/pgbouncer
chown -R pgbouncer:postgres /var/log/pgbouncer
rm -f /var/run/pgbouncer/.pidfile
PGBOUNCER_DATABASES="${PGBOUNCER_DATABASES:-}"
if [[ -n "$PGBOUNCER_DATABASES" ]]; then
  PGBOUNCER_DATABASES="$(printf '%s' "$PGBOUNCER_DATABASES" | tr ';' '\n')"
  export PGBOUNCER_DATABASES=$'\n'"$PGBOUNCER_DATABASES"
else
  export PGBOUNCER_DATABASES=""
fi
envsubst </usr/local/etc/pgbouncer/pgbouncer.ini >/var/run/pgbouncer/pgbouncer.ini
pgbouncer /var/run/pgbouncer/pgbouncer.ini >/proc/1/fd/1 2>/proc/1/fd/2 &
pgbouncer-haproxy-agent

exec su-exec postgres /venv/bin/patroni /venv/etc/patroni.yml
