#!/usr/bin/env bash

set -e

function read_secret_var() {
  local var="$1"
  local file_var="${var}_FILE"
  local current_val="${!var:-}"
  local file_path="${!file_var:-}"
  local file_val
  if [[ -z "$current_val" && -n "$file_path" && -r "$file_path" ]]; then
    if IFS= read -r file_val <"$file_path" || true; then
      export "$var"="$file_val"
    fi
  fi
}

mkdir -p /var/lib/postgresql/data
chown postgres:postgres /var/lib/postgresql/data
chmod 0750 /var/lib/postgresql/data

mkdir -p /run/postgresql
chown postgres:postgres /run/postgresql
chmod 0750 /run/postgresql

if [[ -z "$CLUSTER" ]]; then
  echo "Missing CLUSTER var"
  exit 1
fi

read_secret_var POSTGRES_SU_PWD
read_secret_var POSTGRES_REPL_PWD
read_secret_var POSTGRES_REWIND_PWD
read_secret_var PGBOUNCER_PWD
read_secret_var BACKUP_PATH
read_secret_var BACKUP_REGION
read_secret_var BACKUP_ACCESS_KEY
read_secret_var BACKUP_SECRET_KEY
read_secret_var RESTORE_PATH
read_secret_var RESTORE_REGION
read_secret_var RESTORE_ACCESS_KEY
read_secret_var RESTORE_SECRET_KEY

export BACKUP_NAME="${BACKUP_NAME:=$CLUSTER}"

export RESTORE_NAME="${RESTORE_NAME:=$BACKUP_NAME}"
export RESTORE_PATH="${RESTORE_PATH:=$BACKUP_PATH}"
export RESTORE_REGION="${RESTORE_REGION:=$BACKUP_REGION}"
export RESTORE_ACCESS_KEY="${RESTORE_ACCESS_KEY:=$BACKUP_ACCESS_KEY}"
export RESTORE_SECRET_KEY="${RESTORE_SECRET_KEY:=$BACKUP_SECRET_KEY}"

envsubst </venv/etc/patroni-template.yml >/venv/etc/patroni.yml

write-pgbackrest-conf

export PGPASSFILE=/tmp/pgpass0

export PGBOUNCER_PWD="${PGBOUNCER_PWD:=password}"
rm -f /usr/local/etc/pgbouncer/userlist.txt
echo "\"pgbouncer\" \"${PGBOUNCER_PWD}\"" >/usr/local/etc/pgbouncer/userlist.txt
pgbouncer -d -q /usr/local/etc/pgbouncer/pgbouncer.ini
pgbouncer-haproxy-agent

exec su-exec postgres /venv/bin/patroni /venv/etc/patroni.yml
