scope: ${CLUSTER}
name: ${HOSTNAME}

restapi:
  listen: 0.0.0.0:8008
  connect_address: ${HOSTNAME}:8008
  certfile: /usr/local/etc/ssl/server.crt
  keyfile: /usr/local/etc/ssl/server.key
  cafile: /usr/local/etc/ssl/ca-root.crt
  verify_client: required
# authentication not needed due to client cert requirement
# use authentication if tls is disabled
#  authentication:
#    username: username
#    password: password

ctl:
  insecure: false
  certfile: /usr/local/etc/ssl/server.crt
  keyfile: /usr/local/etc/ssl/server.key
  cafile: /usr/local/etc/ssl/ca-root.crt

etcd3:
  hosts: ${ETCD_HOSTS}
  protocol: https
  cert: /usr/local/etc/ssl/client.crt
  key: /usr/local/etc/ssl/client.key
  cacert: /usr/local/etc/ssl/ca-root.crt

# The bootstrap configuration. Works only when the cluster is not yet initialized.
# If the cluster is already initialized, all changes in the `bootstrap` section are ignored!
bootstrap:
  # This section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`.
  # WARNING! If you want to change any of the parameters that were set up
  # via `bootstrap.dcs` section, please use `patronictl edit-config`!
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    #    primary_start_timeout: 300
    #    synchronous_mode: false
    #standby_cluster:
    #host: 127.0.0.1
    #port: 1111
    #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      pg_hba:
        - local postgres pgbouncer peer
        - local all all scram-sha-256
        # - host replication ${POSTGRES_REPL_USER} 127.0.0.1/32 scram-sha-256
        # - host replication ${POSTGRES_REPL_USER} ::1/128 scram-sha-256
        # - host replication ${POSTGRES_REPL_USER} ${POSTGRES_SUBNET} scram-sha-256
        # - host all all ${POSTGRES_SUBNET} scram-sha-256
        # - host all all 127.0.0.1/32 scram-sha-256
        # - host all all ::1/128 scram-sha-256
        - hostssl replication ${POSTGRES_REPL_USER} 127.0.0.1/32 scram-sha-256
        - hostssl replication ${POSTGRES_REPL_USER} ::1/128 scram-sha-256
        - hostssl replication ${POSTGRES_REPL_USER} ${POSTGRES_SUBNET} scram-sha-256
        - hostssl all all ${POSTGRES_SUBNET} scram-sha-256
        - hostssl all all 127.0.0.1/32 scram-sha-256
        - hostssl all all ::1/128 scram-sha-256
      #      use_slots: true
      parameters:
        #        wal_level: hot_standby
        #        hot_standby: "on"
        #        max_connections: 100
        #        max_worker_processes: 8
        #        wal_keep_segments: 8
        #        max_wal_senders: 10
        #        max_replication_slots: 10
        #        max_prepared_transactions: 0
        #        max_locks_per_transaction: 64
        #        wal_log_hints: "on"
        #        track_commit_timestamp: "off"
        # BACKUP_BEGIN
        archive_mode: "on"
        archive_timeout: ${POSTGRES_ARCHIVE_TIMEOUT}
        archive_command: pgbackrest --stanza=${BACKUP_NAME} --log-level-console=warn --log-level-file=off archive-push "%p"
        restore_command: pgbackrest --stanza=${BACKUP_NAME} --log-level-console=warn --log-level-file=off archive-get %f "%p"
        # BACKUP_END
        ssl: "on"
        ssl_cert_file: "/usr/local/etc/ssl/server.crt"
        ssl_key_file: "/usr/local/etc/ssl/server.key"
        ssl_ca_file: "/usr/local/etc/ssl/ca-root.crt"
        ssl_min_protocol_version: "TLSv1.2"
        ssl_prefer_server_ciphers: "on"

  # bootstrap using pgbackrest
  method: pgbackrest

  pgbackrest:
    command: patroni-bootstrap
    keep_existing_recovery_conf: true
    no_params: false
    # RESTORE_BEGIN
    recovery_conf:
      recovery_target_timeline: latest
      recovery_target_action: promote
      restore_command: pgbackrest --stanza=${RESTORE_NAME} --log-level-console=warn --log-level-file=off archive-get %f "%p"
    # RESTORE_END

  post_bootstrap: patroni-post-bootstrap

  # initdb:
  #   - encoding: UTF8
  #   - data-checksums

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ${HOSTNAME}:5432
  proxy_address: ${HOSTNAME}:6432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/bin
  # pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: ${POSTGRES_SU_USER}
      password: ${POSTGRES_SU_PWD}
    replication:
      username: ${POSTGRES_REPL_USER}
      password: ${POSTGRES_REPL_PWD}
    rewind:
      username: ${POSTGRES_REWIND_USER}
      password: ${POSTGRES_REWIND_PWD}
  parameters:
    unix_socket_directories: /run/postgresql
  #pre_promote: /path/to/pre_promote.sh
  create_replica_methods:
    # BACKUP_BEGIN
    - pgbackrest
    # BACKUP_END
    - basebackup
  # BACKUP_BEGIN
  pgbackrest:
    command: pgbackrest --stanza=${BACKUP_NAME} --log-level-console=warn --log-level-file=off restore --type=none
    keep_data: true
    no_params: true
  # BACKUP_END
  basebackup:
    checkpoint: "fast"
  callbacks:
    # on_start: patroni-callback
    # on_role_change: patroni-callback

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
  # failover_priority: 1
  # sync_priority: 1
  noloadbalance: false
  clonefrom: false
  nostream: false
