#!/usr/bin/env bash

BACKUP_NAME="${BACKUP_NAME:=$CLUSTER}"

STANZA_STATE=$(pgbackrest --stanza="$BACKUP_NAME" --output=json info | jq -r .[0].status.message)

echo "Backup stanza $BACKUP_NAME: $STANZA_STATE"

if [ "$STANZA_STATE" != "ok" ]; then
  # stanza missing - create stanza
  echo "Creating backup stanza $BACKUP_NAME"
  pgbackrest --stanza="$BACKUP_NAME" --log-level-console=detail stanza-create
  pgbackrest --stanza="$BACKUP_NAME" --log-level-console=detail --type=full backup
fi
