#!/usr/bin/env bash

set -euo pipefail

if [[ -z "$RESTORE_NAME" ]]; then
  echo "Error: Missing RESTORE_NAME."
  exit 1
fi

STANZA_STATE=$(pgbackrest --stanza="$RESTORE_NAME" --output=json info | jq -r .[0].status.message)

echo "Backup stanza $RESTORE_NAME: $STANZA_STATE"

if [ "$STANZA_STATE" == "ok" ]; then
  # stanza ok - restore db
  echo "Restoring from backup stanza $RESTORE_NAME"
  pgbackrest --stanza="$RESTORE_NAME" --log-level-console=detail restore
else
  # stanza missing - init db
  # patroni-post-bootstrap.sh will create stanza when primary is available
  echo "No backup stanza - init db"
  initdb -D /var/lib/postgresql/data --encoding UTF8 --data-checksums
  touch /var/run/postgresql/post-init-db
fi
