#!/usr/bin/env bash

set -euo pipefail

if [[ -z "${BACKUP_PATH:-}" ]]; then
  echo "Skipping backup stanza init: BACKUP_PATH not set"
  exit 0
fi

BACKUP_NAME="${BACKUP_NAME:=$CLUSTER}"

STANZA_STATE=$(pgbackrest --stanza="$BACKUP_NAME" --output=json info | jq -r .[0].status.message)

if [[ "$RESTORE_NAME" != "$BACKUP_NAME" ]] && [[ "$STANZA_STATE" == "ok" ]]; then
  # db has been restored from a different stanza, delete existing backup stanza and recreate
  echo "Deleting backup stanza $BACKUP_NAME to recreate from restore stanza $RESTORE_NAME"
  pgbackrest --stanza="$BACKUP_NAME" stop
  pgbackrest --stanza="$BACKUP_NAME" stanza-delete --log-level-file=off --force
  STANZA_STATE="recreate"
fi

echo "Backup stanza $BACKUP_NAME: $STANZA_STATE"

if [ "$STANZA_STATE" != "ok" ]; then
  # stanza missing - create stanza
  echo "Creating backup stanza $BACKUP_NAME"
  pgbackrest --stanza="$BACKUP_NAME" --log-level-console=info --log-level-file=off stanza-create
  pgbackrest --stanza="$BACKUP_NAME" --log-level-console=info --log-level-file=off --type=full backup
fi
