#!/usr/bin/env bash

upgrade_pg_data() {
  echo "[upgrade] Started"

  local DATADIR="/var/lib/postgresql/data"

  # upgrade backup (it's using the old database system identifier)
  su-exec postgres pgbackrest --stanza=${BACKUP_NAME} --no-online stanza-upgrade || {
    echo "[upgrade] pgbackrest stanza-upgrade failed"
    echo "[upgrade] Failed"
    return 1
  }

  if ! command -v pg_upgrade >/dev/null 2>&1; then
    echo "[upgrade] pg_upgrade not found"
    echo "[upgrade] Failed"
    return 1
  fi

  if [[ ! -s "$DATADIR/PG_VERSION" ]]; then
    echo "[upgrade] Cluster missing – nothing to do"
    return 0
  fi

  local OLD_VER NEW_VER
  OLD_VER=$(tr -d '\n' <"$DATADIR/PG_VERSION")
  NEW_VER=$(postgres -V | awk '{print $NF}' | cut -d. -f1)

  if [[ "$OLD_VER" == "$NEW_VER" ]]; then
    echo "[upgrade] Cluster at major version $NEW_VER – nothing to do"
    return 0
  fi

  apk add --no-cache "postgresql${OLD_VER}" "postgresql${OLD_VER}-contrib"

  local OLD_BINDIR="/usr/libexec/postgresql${OLD_VER}"
  local NEW_BINDIR="/usr/libexec/postgresql${NEW_VER}"

  if [[ ! -x "$NEW_BINDIR/postgres" ]]; then
    echo "[upgrade] Invalid new bin path $NEW_BINDIR"
    echo "[upgrade] Failed"
    return 1
  fi
  if [[ ! -x "$OLD_BINDIR/postgres" ]]; then
    echo "[upgrade] Invalid old bin path $OLD_BINDIR"
    echo "[upgrade] Failed"
    return 1
  fi

  local NEW_DATADIR="${DATADIR}.new"
  rm -rf "$NEW_DATADIR"

  echo "[upgrade] Initializing new cluster at $NEW_DATADIR (target $NEW_VER)"

  su-exec postgres initdb -D "$NEW_DATADIR" --encoding UTF8 --data-checksums || {
    echo "[upgrade] initdb failed"
    echo "[upgrade] Failed"
    return 1
  }

  pushd "$DATADIR" >/dev/null

  export PGPASSWORD="$POSTGRES_SU_PWD"

  echo "[upgrade] pg_upgrade check ($OLD_VER → $NEW_VER)"
  su-exec postgres pg_upgrade -d "$DATADIR" -D "$NEW_DATADIR" -b "$OLD_BINDIR" -B "$NEW_BINDIR" --link --check || {
    echo "[upgrade] pg_upgrade --check failed"
    echo "[upgrade] Failed"
    return 1
  }

  echo "[upgrade] pg_upgrade ($OLD_VER → $NEW_VER)"
  su-exec postgres pg_upgrade -d "$DATADIR" -D "$NEW_DATADIR" -b "$OLD_BINDIR" -B "$NEW_BINDIR" --link || {
    echo "[upgrade] pg_upgrade failed"
    echo "[upgrade] Failed"
    return 1
  }

  popd >/dev/null

  # switch data directories
  local TS
  TS=$(date +%s)
  OLD_DATADIR="${DATADIR}.old-${OLD_VER}-${TS}"
  mv "$DATADIR" "$OLD_DATADIR"
  mv "$NEW_DATADIR" "$DATADIR"
  chown -R postgres:postgres "$DATADIR"
  chmod 0750 "$DATADIR"
  echo "[upgrade] Old data directory moved to ${OLD_DATADIR}"

  # remove patroni cluster (it's using the old database system identifier)
  echo -e "${CLUSTER}\nYes I am aware" | patronictl remove "$CLUSTER" || {
    echo "[upgrade] Patroni cluster remove failed"
    echo "[upgrade] Failed"
    return 1
  }
  echo "[upgrade] Patroni cluster removed due to database system identifier change, it will recreated on startup"

  # backup database (it's using the old database system identifier)
  su-exec postgres pgbackrest --stanza=${BACKUP_NAME} --no-online --log-level-console=info --log-level-file=off stanza-upgrade || {
    echo "[upgrade] pgBackRest stanza-upgrade failed"
    echo "[upgrade] Failed"
    return 1
  }
  echo "[upgrade] Full backup complete"

  # update to new system identifier
  PG_SYSID=$(pg_controldata -D /var/lib/postgresql/data | fgrep 'Database system identifier' | awk '{print $NF}')
  echo "[upgrade] New database system identifier: $PG_SYSID"

  # Vacuum database
  echo "[upgrade] Start postgres for vacuum"
  su-exec postgres "$NEW_BINDIR/pg_ctl" -D "$DATADIR" -w -t 120 -o "-c listen_addresses='' -c unix_socket_directories='/run/postgresql'" start || {
    echo "[upgrade] Failed to start postgres"
    echo "[upgrade] Failed"
    return 1
  }

  echo "[upgrade] Vacuum database"
  su-exec postgres vacuumdb -h /run/postgresql -U postgres --all --analyze-in-stages --missing-stats-only
  su-exec postgres vacuumdb -h /run/postgresql -U postgres --all --analyze-only

  echo "[upgrade] Stop postgres"
  su-exec postgres "$NEW_BINDIR/pg_ctl" -D "$DATADIR" -m fast -w stop || {
    echo "[upgrade] Failed to stop postgres"
    echo "[upgrade] Failed"
    return 1
  }

  echo "[upgrade] Complete: $OLD_VER → $NEW_VER"

  return 0
}
