services:
  gen-ca:
    build:
      context: .
      dockerfile: Dockerfile
    image: gen-ca:latest
    volumes:
      - ./certs:/usr/local/etc/ssl
    environment:
      CERT_CN:
      CERT_KEY_ALGO:
      CERT_KEY_SIZE:
      CERT_C:
      CERT_ST:
      CERT_L:
      CERT_O:
      CERT_OU:
      CERT_EXPIRE:
